package io.pleo.antaeus.core.exceptions

class ExternalServiceNotAvailableException : Exception("There have been too many retries. Try later.")